# envsubst < config.toml.in > config.toml
log-level='DEBUG'
relay=true
store=false
filter=false
lightpush=false
rln-relay=false
rpc=true
rpc-admin=true
rpc-private=true
rpc-address='0.0.0.0'
rpc-port=8546
staticnode=[
  '/dns4/relayer.of.holdings/tcp/60000/p2p/16Uiu2HAmMUjGmiUhJeiZgu6ZZnLRkE2VViR2JgjqtW9aTZnHQqgg',
  '/dns4/fleet.wecamefromapes.com/tcp/60000/p2p/16Uiu2HAkyCqm8368Z1Y1pvrBcQQtb66Mjj7uvyAKGdwur3uCbqfb',
  '/dns4/fleet.wecamefromapes.com/tcp/60001/p2p/16Uiu2HAmTCCZFbQxDNF1TL9TKSPXtfF9QJtNWhCFE5M8UNzk7DQv',
  '/dns4/fleet.wecamefromapes.com/tcp/60002/p2p/16Uiu2HAm2g9z6PyWCAe6RXXQto6ykD4EM6YH67mmQYfBQtb6ZxFi',
  '/dns4/fleet.wecamefromapes.com/tcp/60003/p2p/16Uiu2HAmDii55GGfHZBz1XsJD6xmmC22baFyYQMaygv8a1yiuvEw',
  '/dns4/fleet.wecamefromapes.com/tcp/60004/p2p/16Uiu2HAmCEDPo7wFZUdFT3iE8ntAxTxRSZHKs6cEf9Rg44NwduNr',
  '/dns4/fleet.wecamefromapes.com/tcp/60005/p2p/16Uiu2HAkzkgDGEEah58RpR8ooFg3YbRhxJZ3pRZiZm3KGWreBfiw'
]
dns-discovery=false
discv5-discovery=false
discv5-bootstrap-node=[

]
pubsub-topic=['/waku/2/railgun-relayer']
metrics-server=false
max-connections=300
