# envsubst < config.toml.in > config.toml
#log-level='DEBUG'
relay=true
store=false
filter=true
lightpush=true
rln-relay=false
relay-peer-exchange=true
rest=true
rest-address='0.0.0.0'
rest-port=8546
rest-admin=true
#rest-private=true
rest-relay-cache-capacity=3000
keep-alive=true
staticnode=[
 # dev-node
  "/dns4/core.rootedinprivacy.com/tcp/60000/p2p/16Uiu2HAm4Ai1GzKv4EykU26ST1BPT4AHtABsYCLKrDG74GWX7D6H",
]
dns-discovery=true
discv5-discovery=true
discv5-bootstrap-node=[
  # dev-node
  "enr:-Oi4QN0VJmJmJ5LmdLhZ-Cq9RnbnrtxxGk_sdUQzSXsCxx0mU6NqVrLnrGMbbtaL0fhU6kpbGp4QYDe6HbglzXl6jogBgmlkgnY0gmlwhIxSIGiKbXVsdGlhZGRyc7hAAB02GGNvcmUucm9vdGVkaW5wcml2YWN5LmNvbQbqYAAfNhhjb3JlLnJvb3RlZGlucHJpdmFjeS5jb20GH0DeA4Jyc4UAAAEAAYlzZWNwMjU2azGhAoHjwrFVyJASH7pxKYEEZ1Ob56Fn_r-iG36mOatTnZgSg3RjcILqYIN1ZHCCIyiFd2FrdTIP",
]
max-connections=300
shard=[0, 1, 2, 3, 4, 5]
max-msg-size="512KiB"

cluster-id=0 # needed when switch to 0.33 nwaku, pubsub-topic is deprecated
ip-colocation-limit=30