# envsubst < config.toml.in > config.toml
log-level='debug'
relay=true
store=true
filter=true
lightpush=true
rpc=true
rpc-admin=true
rpc-private=true
rpc-address='0.0.0.0'
rpc-port=8546
persist-peers=true
relay-peer-exchange=false
keep-alive=true
persist-messages=false
#db-path='./store'
ports-shift=0
staticnode=[
  '/dns4/relayer.railgun.org/tcp/60000/p2p/16Uiu2HAmNy49QzXVWHMdhz7DQHXCpk9sHvVua99j3QcShUK8PVSD',
  '/ip4/18.117.34.173/tcp/60000/p2p/16Uiu2HAmEvDM3qLuS1fcAjwgDww9UqutSBCGX6yZEu9sVnLgUomj',
  '/ip4/3.213.246.122/tcp/60000/p2p/16Uiu2HAmLHDo7bHwEs6k6yhWBi1fTrm4WwH48W5wGUps3gVDVFA6',
  '/dns4/relayer.of.holdings/tcp/60000/p2p/16Uiu2HAmMUjGmiUhJeiZgu6ZZnLRkE2VViR2JgjqtW9aTZnHQqgg',
  '/dns4/node-01.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb',
  '/dns4/node-01.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D'
]

nodekey="0x17cfa6e8621229b3ffc8397a04b0802d345a5c905550d205841c9978f5d8c725"
nat="extip:67.177.158.27"
listen-address="0.0.0.0"

## If running a domain and security cert for wss, uncomment lines below and replace DOMAIN and cert paths as required

#dns4-domain-name=""
#websocket-support=true
#websocket-secure-support=true
#websocket-secure-key-path="/etc/letsencrypt/live//privkey.pem"
#websocket-secure-cert-path="/etc/letsencrypt/live//fullchain.pem"
