# envsubst < config.toml.in > config.toml
log-level='DEBUG'
relay=true
store=false
filter=false
lightpush=false
rln-relay=false
rpc=true
rpc-admin=true
rpc-private=true
rpc-address='0.0.0.0'
rpc-port=8546
relay-peer-exchange=true
peer-exchange=true
peer-exchange-node='/dns4/teelf.wecamefromapes.com/tcp/60000/p2p/16Uiu2HAkygexqAtchrhYVqLFBTXFEEZPtz8C8ZnSP6iYy1s22mfW'
keep-alive=false
#listen-address='0.0.0.0'
staticnode=[

]
dns-discovery=false
discv5-discovery=true
discv5-bootstrap-node=[
 # fleet
  'enr:-N-4QAIVqdr5hW0L_ki1k9ri6oSZ84__tLUxyv5gp15aVPNfezCAQp6vryhqAhM6kVy2rNQCCMnAYSJQworVhaZEy1YBgmlkgnY0gmlwhC0gpwuKbXVsdGlhZGRyc7hAAB02GGZsZWV0LndlY2FtZWZyb21hcGVzLmNvbQbqYAAfNhhmbGVldC53ZWNhbWVmcm9tYXBlcy5jb20GH0DeA4lzZWNwMjU2azGhAjglQdea_Nbq0ATBaxLcx4N9XizR4Y8Ghqs-Ksq3WBP-g3RjcILqYIN1ZHCCIyiFd2FrdTIB',
  'enr:-N-4QFSAWPQZszFYZEDTkp1fm6d3t1mPzwH3KBicT0pM2zhRdktoGUdsKB9nS2Uc47kO_kv3Le-mr5lFFduj5fbKWB0BgmlkgnY0gmlwhC0gpwuKbXVsdGlhZGRyc7hAAB02GGZsZWV0LndlY2FtZWZyb21hcGVzLmNvbQbqYQAfNhhmbGVldC53ZWNhbWVmcm9tYXBlcy5jb20GH0HeA4lzZWNwMjU2azGhA9gCbHe9obcRB0Eyxn8uu6K3LoZb2xhLnl_Tc28bl2gbg3RjcILqYYN1ZHCCIymFd2FrdTIB',
  'enr:-N-4QClmmi9wpTvqlkh5qgRIjgNAWmNqrdJ26k8HuiLDto6gPimHQPJSKS48RWfnQzyFMA9J7sOpL8d--puVO24gGP0BgmlkgnY0gmlwhC0gpwuKbXVsdGlhZGRyc7hAAB02GGZsZWV0LndlY2FtZWZyb21hcGVzLmNvbQbqYgAfNhhmbGVldC53ZWNhbWVmcm9tYXBlcy5jb20GH0LeA4lzZWNwMjU2azGhAmu3mvlcqDxq1Hkn9FQvAs_VKdms_hYg4V7wvy3tb6Xhg3RjcILqYoN1ZHCCIyqFd2FrdTIB',
]
topic=[
  '/waku/2/railgun-relayer',
]
metrics-server=false
max-connections=300
