# envsubst < config.toml.in > config.toml
log-level='DEBUG'
relay=true
store=false
filter=false
lightpush=false
rln-relay=false
rpc=false
rpc-admin=false
rpc-private=false
rpc-address='0.0.0.0'
rpc-port=8546
relay-peer-exchange=true
rest=true
rest-address='0.0.0.0'
rest-port=8546
rest-admin=true
rest-private=true
rest-relay-cache-capacity=300
staticnode=[
  '/dns4/fleet.wecamefromapes.com/tcp/60000/p2p/16Uiu2HAkyCqm8368Z1Y1pvrBcQQtb66Mjj7uvyAKGdwur3uCbqfb',
  '/dns4/fleet.wecamefromapes.com/tcp/60001/p2p/16Uiu2HAmTCCZFbQxDNF1TL9TKSPXtfF9QJtNWhCFE5M8UNzk7DQv',
  '/dns4/fleet.wecamefromapes.com/tcp/60002/p2p/16Uiu2HAm2g9z6PyWCAe6RXXQto6ykD4EM6YH67mmQYfBQtb6ZxFi',
  #'/dns4/fleet.wecamefromapes.com/tcp/60003/p2p/16Uiu2HAmDii55GGfHZBz1XsJD6xmmC22baFyYQMaygv8a1yiuvEw',
  #'/dns4/fleet.wecamefromapes.com/tcp/60004/p2p/16Uiu2HAmCEDPo7wFZUdFT3iE8ntAxTxRSZHKs6cEf9Rg44NwduNr',
  #'/dns4/fleet.wecamefromapes.com/tcp/60005/p2p/16Uiu2HAkzkgDGEEah58RpR8ooFg3YbRhxJZ3pRZiZm3KGWreBfiw'
]
dns-discovery=false
discv5-discovery=false
discv5-bootstrap-node=[
  # fleet
  'enr:-Ni4QNUg5tVpxoM2g3Xy-m5ASzZ3jjPxTJt2oeASwNa0d4gTFfGaKu4HvXgvoS-t9RWfynLzWZO-WUmG6RnGwhPD84sBgmlkgnY0gmlwhC0gpwuKbXVsdGlhZGRyc7hAAB02GGZsZWV0LndlY2FtZWZyb21hcGVzLmNvbQbqYAAfNhhmbGVldC53ZWNhbWVmcm9tYXBlcy5jb20GH0DeA4lzZWNwMjU2azGhAjglQdea_Nbq0ATBaxLcx4N9XizR4Y8Ghqs-Ksq3WBP-g3RjcILqYIV3YWt1MgE',
  # roh
  'enr:-Lq4QDa0zxNXjR6g_WSroaQnZDVG7FoIxhTyrvnFAhiX9GqsKAN7u4cyQDDzYnuPLzaN0gmUvZD90UsTAJ9PjDcjlMYBgmlkgnY0gmlwhKdH8B6KbXVsdGlhZGRyc5wAGjYTcmVsYXllci5vZi5ob2xkaW5ncwYfQN4DiXNlY3AyNTZrMaEDgxhTW1QQXUp6rmDAj8RflocYG0_fxiW9GnU_pzl_7XWDdGNwgupgg3VkcIIjKIV3YWt1MgE',
  # crabdance
  'enr:-JK4QBT-bx8uZP7cUQGcIyY9yKJfwDf4_MBw9IXnN7DcH4nPaYXz1JhdQALBvKLw8O1WqrfLfaUwLlBcIWXgJNdCihMBgmlkgnY0gmlwhF-zg3qJc2VjcDI1NmsxoQLQiUl_Ut_tI9UQR48EhPOAe73wbHrk7OZ2KBhu2DmL6YN0Y3CC6mCDdWRwgiMohXdha3UyAQ',
  # mooo.1
  'enr:-Mm4QBgzTiBP0DRTX2IJEddmyXDlp4ksa5Pd_U89NqFHaYfIdq0kR86R_CIyIbilTxMiLIXEpNPH5b9GtrNcjH-mfB8BgmlkgnY0gmlwhLymEG-KbXVsdGlhZGRyc7IAFjYRcmVsYXlvb3IubW9vby5jb20G6mAAGDYRcmVsYXlvb3IubW9vby5jb20GH0DeA4lzZWNwMjU2azGhA_1kEF1l8QT569PdgB4M3oz-8RT6du_I_hvcn9l5i3_bg3RjcILqYIV3YWt1MgE',
  # mooo.2
  'enr:-Mm4QCaldC7HjHnvB_6_Ocxwqhkycd0FKNbALd9BG3y2cchqDU4FQp6aSINa0JLm_uui0-WpdJX81fjxXe8fIHBkVJMBgmlkgnY0gmlwhLymEG-KbXVsdGlhZGRyc7IAFjYRcmVsYXlvb3IubW9vby5jb20G6mEAGDYRcmVsYXlvb3IubW9vby5jb20GH0HeA4lzZWNwMjU2azGhAw86lFAUG_eqcBrrISwvK-R2jUBjuuZtRhP7uKzPzi-Kg3RjcILqYYV3YWt1MgE'
]
pubsub-topic=[
  '/waku/2/railgun-relayer',
]
metrics-server=false
max-connections=300
