# envsubst < config.toml.in > config.toml
log-level='DEBUG'
relay=true
store=false
filter=false
lightpush=false
rln-relay=false
rpc=true
rpc-admin=true
rpc-private=true
rpc-address='0.0.0.0'
rpc-port=8546
relay-peer-exchange=true
peer-exchange-node='/dns4/relayer.of.holdings/tcp/60000/p2p/16Uiu2HAmMUjGmiUhJeiZgu6ZZnLRkE2VViR2JgjqtW9aTZnHQqgg'
#keep-alive=true
listen-address="0.0.0.0"
staticnode=[
  '/dns4/dev.of.holdings/tcp/60000/p2p/16Uiu2HAmKjyaCBNtnRyyUeVefpCA88fm9TqY1XFQSnCmkLmvFh2X',
  '/dns4/relayer.crabdance.com/tcp/60000/p2p/16Uiu2HAm9TiCU9ZRPoKMUyo6QQvZTSceSH5ZtX6u353NHgVCtr1W',
  '/dns4/relayer.chickenkiller.com/tcp/60000/p2p/16Uiu2HAmNy49QzXVWHMdhz7DQHXCpk9sHvVua99j3QcShUK8PVSD',
  '/ip4/18.117.34.173/tcp/60000/p2p/16Uiu2HAmEvDM3qLuS1fcAjwgDww9UqutSBCGX6yZEu9sVnLgUomj',
  '/dns4/relayer.of.holdings/tcp/60000/p2p/16Uiu2HAmMUjGmiUhJeiZgu6ZZnLRkE2VViR2JgjqtW9aTZnHQqgg',
]
dns-discovery=false
#dns-discovery-url='enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im'
discv5-discovery=true
discv5-bootstrap-node=[
  # roh
  'enr:-Lq4QDa0zxNXjR6g_WSroaQnZDVG7FoIxhTyrvnFAhiX9GqsKAN7u4cyQDDzYnuPLzaN0gmUvZD90UsTAJ9PjDcjlMYBgmlkgnY0gmlwhKdH8B6KbXVsdGlhZGRyc5wAGjYTcmVsYXllci5vZi5ob2xkaW5ncwYfQN4DiXNlY3AyNTZrMaEDgxhTW1QQXUp6rmDAj8RflocYG0_fxiW9GnU_pzl_7XWDdGNwgupgg3VkcIIjKIV3YWt1MgE',
  # crabdance
  'enr:-JK4QBT-bx8uZP7cUQGcIyY9yKJfwDf4_MBw9IXnN7DcH4nPaYXz1JhdQALBvKLw8O1WqrfLfaUwLlBcIWXgJNdCihMBgmlkgnY0gmlwhF-zg3qJc2VjcDI1NmsxoQLQiUl_Ut_tI9UQR48EhPOAe73wbHrk7OZ2KBhu2DmL6YN0Y3CC6mCDdWRwgiMohXdha3UyAQ',
  # mooo.1
  'enr:-Mm4QBgzTiBP0DRTX2IJEddmyXDlp4ksa5Pd_U89NqFHaYfIdq0kR86R_CIyIbilTxMiLIXEpNPH5b9GtrNcjH-mfB8BgmlkgnY0gmlwhLymEG-KbXVsdGlhZGRyc7IAFjYRcmVsYXlvb3IubW9vby5jb20G6mAAGDYRcmVsYXlvb3IubW9vby5jb20GH0DeA4lzZWNwMjU2azGhA_1kEF1l8QT569PdgB4M3oz-8RT6du_I_hvcn9l5i3_bg3RjcILqYIV3YWt1MgE',
  # mooo.2
  'enr:-Mm4QCaldC7HjHnvB_6_Ocxwqhkycd0FKNbALd9BG3y2cchqDU4FQp6aSINa0JLm_uui0-WpdJX81fjxXe8fIHBkVJMBgmlkgnY0gmlwhLymEG-KbXVsdGlhZGRyc7IAFjYRcmVsYXlvb3IubW9vby5jb20G6mEAGDYRcmVsYXlvb3IubW9vby5jb20GH0HeA4lzZWNwMjU2azGhAw86lFAUG_eqcBrrISwvK-R2jUBjuuZtRhP7uKzPzi-Kg3RjcILqYYV3YWt1MgE'
]
topic=[
  '/waku/2/railgun-relayer',
#  '/waku/2/default-waku/proto'
]
metrics-server=true
max-connections=200
