# envsubst < config.toml.in > config.toml
#log-level='DEBUG'
relay=true
store=false
filter=true
lightpush=true
rln-relay=false
relay-peer-exchange=true
rest=true
rest-address='0.0.0.0'
rest-port=8546
rest-admin=true
#rest-private=true
rest-relay-cache-capacity=3000
keep-alive=false
staticnode=[
 # dev-node
  "/dns4/core.rootedinprivacy.com/tcp/60000/p2p/16Uiu2HAm4Ai1GzKv4EykU26ST1BPT4AHtABsYCLKrDG74GWX7D6H",
]
dns-discovery=false
discv5-discovery=false
discv5-bootstrap-node=[
  # dev-node
  "enr:-Ou4QF5uFxGUG9WVUuysEWm8nketT_Pe6hG0P6NRxu9dTOwHWHWQgGFhm-vqmYwUvU0LtrW2LhSEO7iEHKD4l8JEd14BgmlkgnY0gmlwhIxSIGiKbXVsdGlhZGRyc7hAAB02GGNvcmUucm9vdGVkaW5wcml2YWN5LmNvbQbqYAAfNhhjb3JlLnJvb3RlZGlucHJpdmFjeS5jb20GH0DeA4Jyc48AAAYAAAABAAIAAwAEAAWJc2VjcDI1NmsxoQKB48KxVciQEh-6cSmBBGdTm-ehZ_6_oht-pjmrU52YEoN0Y3CC6mCFd2FrdTIN",
]
shard=[0, 1, 2, 3, 4, 5]
max-msg-size="512KiB"

cluster-id=0 # needed when switch to 0.33 nwaku, pubsub-topic is deprecated
filter-subscription-timeout=3000
filter-max-peers-to-serve=10000
reliability=false
num-shards-in-network=6

peer-store-capacity=500
max-connections=500
max-relay-peers=500
ip-colocation-limit=100
peer-persistence=false
