# envsubst < config.toml.in > config.toml
# log-level='DEBUG'
relay=true
store=false
filter=true
lightpush=true
rln-relay=false
relay-peer-exchange=true
rest=true
rest-address='0.0.0.0'
rest-port=8546
rest-admin=true
rest-private=true
rest-relay-cache-capacity=3000
keep-alive=true
dns-discovery=false
discv5-discovery=false
max-connections=300
shard=[0,1,2,3,4,5]
