# envsubst < config.toml.in > config.toml
log-level='DEBUG'
relay=true
store=false
filter=false
lightpush=false
rln-relay=false
rpc=true
rpc-admin=true
rpc-private=true
rpc-address='0.0.0.0'
rpc-port=8546
relay-peer-exchange=true
peer-exchange=true
peer-exchange-node='/dns4/teelf.wecamefromapes.com/tcp/60000/p2p/16Uiu2HAkygexqAtchrhYVqLFBTXFEEZPtz8C8ZnSP6iYy1s22mfW'
keep-alive=false
#listen-address='0.0.0.0'
staticnode=[

]
dns-discovery=false
discv5-discovery=false
discv5-bootstrap-node=[

]
topic=[
  '/waku/2/railgun-relayer',
]
metrics-server=false
max-connections=300
