# envsubst < config.toml.in > config.toml
log-level='DEBUG'
relay=true
store=false
filter=true
lightpush=true
rln-relay=false
relay-peer-exchange=true
rest=true
rest-address='0.0.0.0'
rest-port=8546
rest-admin=true
rest-private=true
rest-relay-cache-capacity=3000
keep-alive=true
staticnode=[
 # this node"/dns4/fleet.rootedinprivacy.com/tcp/60000/p2p/16Uiu2HAm3GnUDQhBfax298CMkZX9MBHTJ9B8GXhrbueozESUaRZP",
 # this node "/dns4/fleet.rootedinprivacy.com/tcp/8000/wss/p2p/16Uiu2HAm3GnUDQhBfax298CMkZX9MBHTJ9B8GXhrbueozESUaRZP"
 # "/dns4/horsey.horsewithsixlegs.xyz/tcp/60000/p2p/16Uiu2HAmLWDFk5nGXgLx2Mz2deiEMRya1HNcvWELMDodkAC891Sd",
 # "/dns4/waku.wecamefromapes.com/tcp/60000/p2p/16Uiu2HAmATh6oki7ZCQEpCH2P9A1A2UXSRdVuU1hn9mzR3NKarPN",
 # "/dns4/zebra.horsewithsixlegs.xyz/tcp/60000/p2p/16Uiu2HAm4LeP19jWXhQ6ayMX27vPYKGAo3WQeeFYrVDJ2nBi9gjv",
 # "/dns4/giraffe.horsewithsixlegs.xyz/tcp/60000/p2p/16Uiu2HAm6EBg9G12QTbL4UbRGgRW7GnWzAghCZskgwahtPUT1Fvf"

 # dev-node
  "/dns4/core.rootedinprivacy.com/tcp/60000/p2p/16Uiu2HAm4Ai1GzKv4EykU26ST1BPT4AHtABsYCLKrDG74GWX7D6H",
]
dns-discovery=true
discv5-discovery=true
discv5-bootstrap-node=[
  # dev-node
  "enr:-Oi4QN0VJmJmJ5LmdLhZ-Cq9RnbnrtxxGk_sdUQzSXsCxx0mU6NqVrLnrGMbbtaL0fhU6kpbGp4QYDe6HbglzXl6jogBgmlkgnY0gmlwhIxSIGiKbXVsdGlhZGRyc7hAAB02GGNvcmUucm9vdGVkaW5wcml2YWN5LmNvbQbqYAAfNhhjb3JlLnJvb3RlZGlucHJpdmFjeS5jb20GH0DeA4Jyc4UAAAEAAYlzZWNwMjU2azGhAoHjwrFVyJASH7pxKYEEZ1Ob56Fn_r-iG36mOatTnZgSg3RjcILqYIN1ZHCCIyiFd2FrdTIP",
]
max-connections=300
pubsub-topic=[
  "/waku/2/rs/0/1"
]
shard=[0, 1, 2, 3, 4, 5]