# envsubst < config.toml.in > config.toml
relay=true
store=false
filter=false
lightpush=false
rpc=true
rpc-admin=true
rpc-private=true
rpc-address='0.0.0.0'
rpc-port=8546
relay-peer-exchange=false
keep-alive=true
ports-shift=0
staticnode=[
  '/dns4/relayer.crabdance.com/tcp/60000/p2p/16Uiu2HAm9TiCU9ZRPoKMUyo6QQvZTSceSH5ZtX6u353NHgVCtr1W',
  '/dns4/relayer.tibet.org/tcp/60000/p2p/16Uiu2HAmNy49QzXVWHMdhz7DQHXCpk9sHvVua99j3QcShUK8PVSD',
  '/ip4/18.117.34.173/tcp/60000/p2p/16Uiu2HAmEvDM3qLuS1fcAjwgDww9UqutSBCGX6yZEu9sVnLgUomj',
  '/dns4/relayer.of.holdings/tcp/60000/p2p/16Uiu2HAmMUjGmiUhJeiZgu6ZZnLRkE2VViR2JgjqtW9aTZnHQqgg',
  '/dns4/railgun.railed.io/tcp/60000/p2p/16Uiu2HAm2jXWaRA9LQnyTwgVRSBz3hNpotRf77gKZNfV6auBwbDG',
  '/dns4/node-01.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb',
  '/dns4/node-01.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D'
]
dns-discovery=true
dns-discovery-url='enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im'
discv5-discovery=true
