version: '3.9'

networks:
  railgun:

volumes:
  waku:
    name: 'waku'
  relayer:
    name: 'relayer'

services:
  waku:
    image: wakunode:latest
    hostname: 'waku'
    ports:
      - 60000:60000
      - 8000:8000
    deploy:
      replicas: 1
    entrypoint: ['/app/run-waku.sh']
    volumes:
      - waku:/mnt

  relayer:
    image: 'relayer:latest'
    hostname: 'relayer'
    deploy:
      replicas: 1
    environment:
      WAKU_RPC_URL: 'http://waku:8546'
      LEPTON_DB: '/mnt/relayer.db'
      LOG_LEVEL: 'debug'
      DEBUG: 'relayer*,waku:jsonrpc-api'
    secrets:
      - MNEMONIC
      - DB_ENCRYPTION_KEY
    depends_on:
      - waku
    volumes:
      - relayer:/mnt

secrets:
  MNEMONIC:
    external: true
  DB_ENCRYPTION_KEY:
    external: true
