version: '3.9'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - URL=${BASEDOMAIN}
      - ONLY_SUBDOMAINS=true
      - SUBDOMAINS=${SUBDOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
    volumes:
      - ./appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
