version: '3.9'

networks:
  railgun:

volumes:
  waku:
    name: 'waku'

services:
  waku:
    image: wakunode:latest
    hostname: "waku"
    ports:
      - 60000:60000
      - 8000:8000
    expose:
      - "8546"
    deploy:
      replicas: 1
    entrypoint: ["/app/run-waku.sh"]
    volumes:
      - waku:/mnt

  hardhat:
    image: 'hhdocker:latest'
    hostname: 'hardhat'
    expose:
      - "8545"
    deploy:
      replicas: 1

  relayer:
    image: 'relayer:new'
    hostname: "relayer"
    deploy:
      replicas: 1
    environment:
      WAKU_RPC_URL: "http://waku:8546"
      HARDHAT_RPC_URL: "http://hardhat:8545"
    secrets:
      - MNEMONIC
      - DB_ENCRYPTION_KEY
    depends_on:
      - waku
      - hardhat
    restart: always

secrets:
  MNEMONIC:
    #    external: true
    file: secret/MNEMONIC
  DB_ENCRYPTION_KEY:
    #    external: true
    file: secret/DB_ENCRYPTION_KEY
