version: '3.9'

volumes:
  nwaku1:
    name: 'nwaku1'
  nwaku2:
    name: 'nwaku2'
  broadcaster:
    name: 'broadcaster'

services:
  nwaku1:
    image: nwaku:latest
    container_name: 'nwaku1'
    hostname: 'nwaku1'
    ports:
      - '60000:60000'
      - '9000:9000'
      - '8000:8000'
      - '8546:8546'
    restart: always
    volumes:
      - nwaku1:/data
      - ./appdata/swag/etc/letsencrypt:/ssl
      - ../scripts/nwaku:/app/scripts
    depends_on:
      - swag
    #entrypoint: tail -F anything
    entrypoint: >
      wakunode2 --config-file=/app/config.toml
      --nat="extip:${EXTIP}"
      --dns4-domain-name=${SUBDOMAIN}.${BASEDOMAIN}
      --nodekey=${NODEKEY_1}
      --websocket-support=true
      --websocket-secure-support=true
      --websocket-secure-key-path="/ssl/live/${SUBDOMAIN}.${BASEDOMAIN}/privkey.pem"
      --websocket-secure-cert-path="/ssl/live/${SUBDOMAIN}.${BASEDOMAIN}/fullchain.pem"

  nwaku2:
    image: nwaku:latest
    container_name: 'nwaku2'
    hostname: 'nwaku2'
    ports:
      - '60001:60001' # p2p
      - '9001:9001' # ENR
      - '8001:8001' # wss
      - '8547:8547'
    volumes:
      - nwaku2:/data
      - ./appdata/swag/etc/letsencrypt:/ssl
      - ../scripts/nwaku:/app/scripts
    depends_on:
      - swag
    entrypoint: >
      wakunode2
        --config-file=/app/config.toml
        --nat="extip:${EXTIP}"
        --nodekey=${NODEKEY_2}
        --dns4-domain-name=${SUBDOMAIN}.${BASEDOMAIN}
        --websocket-support=true
        --websocket-secure-support=true
        --websocket-secure-key-path="/ssl/live/${SUBDOMAIN}.${BASEDOMAIN}/privkey.pem"
        --websocket-secure-cert-path="/ssl/live/${SUBDOMAIN}.${BASEDOMAIN}/fullchain.pem"
        --ports-shift=1

  broadcaster:
    image: 'broadcaster:latest'
    container_name: 'broadcaster'
    hostname: 'broadcaster'
    environment:
      WAKU_RPC_URL: 'http://nwaku:8546'
      LEPTON_DB: '/mnt/broadcaster.db'
      LOG_LEVEL: 'debug'
      DEBUG: 'broadcaster*,waku:jsonrpc-api'
    depends_on:
      - nwaku1
    restart: always
    tty: true
    volumes:
      - broadcaster:/mnt

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - URL=${BASEDOMAIN}
      - ONLY_SUBDOMAINS=true
      - SUBDOMAINS=${SUBDOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
    volumes:
      - ./appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
