name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 12,22 * * *'

jobs:
  unit-tests:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm copy-my-config
      - name: pnpm test up to 3 times
        shell: bash
        run: # Try yarn test 3 times before failing
          r=3;while ! env ZERO_X_API_KEY=${{ secrets.ZERO_X_API_KEY }} pnpm test ; do ((--r))||exit;sleep 1;done
